---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mongo
resources:
  - mongo.service.yaml
  - mongo.statefulset.yaml

configMapGenerator:
  - name: mongo-init
    behavior: create
    files:
      - ../../init_scripts/mongo-init.js
